### ISSUE TITLE
Fix line length issues in YANG module

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#14]
Validating ../bin/ietf-diffserv@2022-02-24.yang
../bin/ietf-diffserv@2022-02-24.yang:317: warning: line length 77 exceeds 72 characters
../bin/ietf-diffserv@2022-02-24.yang:375: warning: line length 81 exceeds 72 characters
../bin/ietf-diffserv@2022-02-24.yang:449: warning: line length 97 exceeds 72 characters
../bin/ietf-diffserv@2022-02-24.yang:454: warning: line length 83 exceeds 72 characters
Validating ../bin/ietf-qos-action@2022-02-24.yang
../bin/ietf-qos-action@2022-02-24.yang:59: warning: line length 74 exceeds 72 characters
../bin/ietf-qos-action@2022-02-24.yang:63: warning: line length 78 exceeds 72 characters
../bin/ietf-qos-action@2022-02-24.yang:67: warning: line length 75 exceeds 72 characters
Validating ../bin/ietf-qos-classifier@2022-02-24.yang
Validating ../bin/ietf-qos-policy@2022-02-24.yang
Validating ../bin/ietf-qos-target@2022-02-24.yang
Validating ../bin/ietf-queue-policy@2022-02-24.yang
../bin/ietf-queue-policy@2022-02-24.yang:74: warning: line length 76 exceeds 72 characters
../bin/ietf-queue-policy@2022-02-24.yang:125: warning: line length 97 exceeds 72 characters
Validating ../bin/ietf-scheduler-policy@2022-02-24.yang
../bin/ietf-scheduler-policy@2022-02-24.yang:83: warning: line length 76 exceeds 72 characters
../bin/ietf-scheduler-policy@2022-02-24.yang:84: warning: line length 77 exceeds 72 characters
../bin/ietf-scheduler-policy@2022-02-24.yang:123: warning: line length 97 exceeds 72 characters
../bin/ietf-scheduler-policy@2022-02-24.yang:124: warning: line length 77 exceeds 72 characters
Generating abridged tree diagram for ../bin/ietf-diffserv@2022-02-24.yang
../bin/ietf-diffserv@2022-02-24.yang:317: warning: line length 77 exceeds 72 characters
../bin/ietf-diffserv@2022-02-24.yang:375: warning: line length 81 exceeds 72 characters
../bin/ietf-diffserv@2022-02-24.yang:449: warning: line length 97 exceeds 72 characters
../bin/ietf-diffserv@2022-02-24.yang:454: warning: line length 83 exceeds 72 characters
Generating abridged tree diagram for ../bin/ietf-qos-action@2022-02-24.yang
../bin/ietf-qos-action@2022-02-24.yang:59: warning: line length 74 exceeds 72 characters
../bin/ietf-qos-action@2022-02-24.yang:63: warning: line length 78 exceeds 72 characters
../bin/ietf-qos-action@2022-02-24.yang:67: warning: line length 75 exceeds 72 characters
Generating abridged tree diagram for ../bin/ietf-qos-classifier@2022-02-24.yang
Generating abridged tree diagram for ../bin/ietf-qos-policy@2022-02-24.yang
Generating abridged tree diagram for ../bin/ietf-qos-target@2022-02-24.yang
Generating abridged tree diagram for ../bin/ietf-queue-policy@2022-02-24.yang
../bin/ietf-queue-policy@2022-02-24.yang:74: warning: line length 76 exceeds 72 characters
../bin/ietf-queue-policy@2022-02-24.yang:125: warning: line length 97 exceeds 72 characters
Generating abridged tree diagram for ../bin/ietf-scheduler-policy@2022-02-24.yang
../bin/ietf-scheduler-policy@2022-02-24.yang:83: warning: line length 76 exceeds 72 characters
../bin/ietf-scheduler-policy@2022-02-24.yang:84: warning: line length 77 exceeds 72 characters
../bin/ietf-scheduler-policy@2022-02-24.yang:123: warning: line length 97 exceeds 72 characters
../bin/ietf-scheduler-policy@2022-02-24.yang:124: warning: line length 77 exceeds 72 characters

**Comment by asechoud** [comment]
This is closed now.

**Comment by asechoud** [comment]
incorporated.
