### ISSUE TITLE
Reexamine the use of feature statements in the model

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#21]
The number of feature statements in the models are huge. Let us examine if we can reduce/remove the number of feature statements in the model.

**Comment by mjethanandani** [comment]
@asechoud, to look at the feature statements, and propose what can be removed.

**Comment by aseemavi** [comment]
There are 16 features. We can remove 12 and keep 4

We can remove below 12:

match-any-filter-type-support            
burst-time-unit-support;        
meter-inline-feature;           
meter-reference-feature;        
queue-action-support;           
scheduler-action-support;       
count-feature                
traffic-group-feature;         
queue-policy-support        
queue-template-support    
queue-inline-support      
scheduler-policy-support;      

Some of these can't co-exist in config; like meter-inline and meter-reference can't co-exist. Hence, a condition need to be added that other config is not present at the same time.

We can keep below 4:

policy-inline-classifier-config
classifier-template-feature
child-policy-feature   
named-counter-feature;
