### ISSUE TITLE
Remove use of -cfg in the node name.

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#24]
Why do you label some rw objects as -cfg? Is not everything rw here
config? It is mainly in the examples:

example-compa-diffserv.yang:     grouping qos-group-cfg {
example-compa-diffserv.yang:       list qos-group-cfg {
example-compa-diffserv.yang:         uses qos-group-cfg;
example-compa-diffserv.yang:             "policy:classifier-action-entry-cfg/" +
example-compa-diffserv.yang:             "policy:action-cfg-params" {
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compa-diffserv.yang:             "/policy:classifier-action-entry-cfg" +
example-compa-diffserv.yang:             "/policy:action-cfg-params" +
example-compb-diffserv-filter-policy.yang:  grouping forwarding-class-cfg {
example-compb-diffserv-filter-policy.yang:    list forwarding-class-cfg {
example-compb-diffserv-filter-policy.yang:  grouping loss-priority-cfg {
example-compb-diffserv-filter-policy.yang:    list loss-priority-cfg {
example-compb-diffserv-filter-policy.yang:        uses forwarding-class-cfg;
example-compb-diffserv-filter-policy.yang:        uses loss-priority-cfg;
example-compb-diffserv-filter-policy.yang:    container mark-fwd-class-cfg {
example-compb-diffserv-filter-policy.yang:    container mark-loss-priority-cfg {
example-compb-diffserv-filter-policy.yang:          "/policy:classifier-action-entry-cfg" +
example-compb-diffserv-filter-policy.yang:          "/diffserv:action-cfg-params" {
example-compb-queue-policy.yang:  grouping forwarding-class-cfg {
example-compb-queue-policy.yang:    leaf forwarding-class-cfg {
example-compb-queue-policy.yang:      case forwarding-class-cfg {
example-compb-queue-policy.yang:        uses forwarding-class-cfg;
example-compb-queue-policy.yang:          "/policy:classifier-action-entry-cfg" {
example-compb-queue-policy.yang:    choice action-cfg-params {
example-compb-queue.yang:       "/queue-cfg" +
example-compb-queue.yang:       "/algorithmic-drop-cfg" +
example-compb-scheduler-policy.yang:             "/policy:classifier-action-entry-cfg" {
example-compb-scheduler-policy.yang:       choice action-cfg-params {
example-compc-qos-policy.yang:               "/pol:classifier-action-entry-cfg" {
example-compc-qos-policy.yang:             "/pol:classifier-action-entry-cfg/pol:action-cfg-params" {
ietf-scheduler-policy.yang:    container match-all-cfg {
ietf-scheduler-policy.yang:  grouping queue-policy-name-cfg {
ietf-scheduler-policy.yang:        uses queue-policy-name-cfg;

**Comment by mjethanandani** [comment]
We have a few more still left.

src/yang/ietf-scheduler-policy.yang:    container match-all-cfg {
src/yang/ietf-scheduler-policy.yang:  grouping queue-policy-name-cfg {
src/yang/ietf-scheduler-policy.yang:        uses queue-policy-name-cfg;

**Comment by aseemavi** [comment]
I don't see any of these

**Comment by mjethanandani** [comment]
Ok.
