### ISSUE TITLE
choice action-params no cases

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#29]
choice action-params has no case statements in ietf-qos-policy. It is empty. Either remove the choice statement or add case statements to it.

**Comment by aseemavi** [comment]
This is based on augmentation. Policy is a framework. It is completed by diffserv policy.

**Comment by mjethanandani** [comment]
Is there an expectation that other policies might augment the action-params node? If not, then you can move the choice statement inside of qos-policy. Otherwise, you can close the issue.

**Comment by mjethanandani** [comment]
See #34
