### ISSUE TITLE
Cleanup example compa, compb and compc files

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#48]
The examples for compa, compb, and compc do not validate. They probably need to be updated to match the changes in the model.

Validating ../bin/example-compa-diffserv@2022-09-26.yang using pyang
../bin/example-compa-diffserv@2022-09-26.yang:1: warning: RFC 8407: 4.1: the module name should start with one of the strings "ietf-" or "iana-"
../bin/example-compa-diffserv@2022-09-26.yang:6: error: module "ietf-qos-classifier" not found in search path
../bin/example-compa-diffserv@2022-09-26.yang:10: error: module "ietf-qos-policy" not found in search path
../bin/example-compa-diffserv@2022-09-26.yang:18: warning: imported module "ietf-diffserv" not used
../bin/example-compa-diffserv@2022-09-26.yang:30: warning: RFC 8407: 3.1: The IETF Trust Copyright statement seems to be missing or is not correct (see pyang --ietf-help for details).
../bin/example-compa-diffserv@2022-09-26.yang:74: error: grouping "threshold" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:79: error: grouping "threshold" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:157: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:184: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:211: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:238: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:265: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:293: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:320: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang:347: error: grouping "drop" not found in module "ietf-qos-action"
../bin/example-compa-diffserv@2022-09-26.yang failed pyang validation

**Comment by aseemavi** [comment]
this must have been fixed by now.

**Comment by mjethanandani** [comment]
There is one PR that is related to this, which is still open. I provided some comments, but they have not been addressed.
