### ISSUE TITLE
What is QoS classification module?

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#52]
The draft says:

`In the ietf-diffserv module, this is realized by augmenting the QoS classification module`

Or does it mean QoS classifier module??

**Comment by aseemavi** [comment]
I think this is already fixed.

**Comment by mjethanandani** [comment]
Hmm. Not according to what I am seeing in GitHub.

**Comment by aseemavi** [comment]
It is fixed here:

https://github.com/mjethanandani/qos-yang/pull/63
