### ISSUE TITLE
This diagram should be in the draft

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#53]
![Picture1](https://user-images.githubusercontent.com/8261320/193707898-426b3b70-4fe4-4cae-a781-bb39f9adceba.png)

**Comment by aseemavi** [comment]
What is the best way to add? As text format? Any example..

**Comment by mjethanandani** [comment]
Yes, text format is what is known, but xml2rfc v3.0 does accept other formats, like SVG.

**Comment by aseemavi** [comment]
Ok, let me use pipes and dashes
