### ISSUE TITLE
Inconsistency between classifier and policy.

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#54]
YANG doctor has identified this inconsistency in the schema tree.

You seem to be inconsistent with nodes for lists. In ietf-qos-classifier
you have

+--rw classifiers
+--rw classifier-entry* [classifier-entry-name]

but in ietf-qos-policy you have

     +--rw classifier-entry* [classifier-entry-name]

**Comment by aseemavi** [comment]
I am missing the point here.. have we taken care of it already

**Comment by aseemavi** [comment]
as per our discussion, closing this issue
