### ISSUE TITLE
Rename features 

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#57]
YANG doctors comment:

_I am not sure I understand feature classifier-template-feature from
the description of it. I am actually lost on the possible
combinations of policy-inline-classifier-config,
classifier-template-feature, match-any-filter-type-support, perhaps
because the descriptions are messed up._

In addition, a feature is called classifier-template-feature (why the suffix -feature), while the other is called policy-inline-classifier-config.

We should come up with better names for both as they define different ways of configuring a classifier. Could this be template-based-classifier and policy-inline-classifier?

**Comment by mjethanandani** [comment]
How about template-based-classifer and inline-policy-classifier?

**Comment by aseemavi** [comment]
this is fixed.. these feature statements are removed after having presence container..
