### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#58]
Opening this as a separate issue, as we will need to do quite a bit of cleanup before publication. One of the comments from YANG doctors is, but is not limited to it is:

_Descriptions need to improve. Some have language issues, others are
simply too short and not very descriptive. I think we like to have
full descriptive sentences in standard YANG modules._

and

_- I am not sure about the choice of prefixes, but there is perhaps no
 consensus on how to choose prefixes. That said, prefixes like
 "target" seem rather generic (but as long as others do not pick such
 generic prefixes...)._

and

_- Do not write "Latest revision for qos actions" if it is the initial
 revision. Ideally, revision statements do not need to change when a
 new revision is created. If you write 'latest revision', well, you
 have to go and make changes._

and

_Why does this document need a normative reference to RFC 6020? Why
 is RFC 6020 referred to in a revision statement??_

**Comment by aseemavi** [comment]
These issues have been taken care of:

- Do not write "Latest revision for qos actions" if it is the initial
revision. Ideally, revision statements do not need to change when a
new revision is created. If you write 'latest revision', well, you
have to go and make changes.

Why does this document need a normative reference to RFC 6020? Why
is RFC 6020 referred to in a revision statement??
