### ISSUE TITLE
logical-not 

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#59]
YANG doctors comment:

_- I do not understand filter-logical-not. This seems to negate
 filter-match-all and filter-match-any. But what do the combinations
 really mean? I assume 'not any' means none, I am not sure what 'not
 all' means, perhaps 'any or none'? Why not simply add another
 filter-match-operation, e.g., filter-match-none?_

**Comment by mjethanandani** [comment]
Update the example in the appendix to add a value for DSCP and add a port definition that shows that all traffic but the DSCP value defined is expected.

**Comment by aseemavi** [comment]
fixed: https://github.com/mjethanandani/qos-yang/pull/new/logical-not-example
