### ISSUE TITLE
Address broken example(s)

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#70]
The examples for the QoS model do not seem to compile anymore.

Validating yang/example-qos-configuration-a.1.1.xml
libyang err : Invalid enumeration value "qt:match-all". (Schema location "/ietf-traffic-policy:classifiers/classifier/filter-operation", data location "/ietf-traffic-policy:classifier[name='my-classifier']", line number 16.)
YANGLINT[E]: Failed to parse input data file "yang/example-qos-configuration-a.1.1.xml".
failed (error code: 0)

These need to be fixed.

**Comment by aseemavi** [comment]
merged
