### ISSUE TITLE
Rename prefixes in some of the modules

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#76]
Some of the modules carry prefixes that are fairly generic and will clash with prefixes defined in other IETF models. Suggest we rename some of them:

action -> qos-action
oper -> dos-oper
policy -> traffic-policy

**Comment by aseemavi** [comment]
It will make the config path much more longer

**Comment by mjethanandani** [comment]
Tom Petch has been coming after YANG models with these prefix names that are generic. You will have to change them. Choice is to it now, or later. You pick.

**Comment by aseemavi** [comment]
has the other yang models have used short forms like traffic-policy => tp or similar
