### ISSUE TITLE
Named vs inline classifiers

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#78]
Is it possible to reduce the duplication of the filter cases for named classifiers and inline classifiers? The constraints on both also seem to differ.

**Comment by aseemavi** [comment]
case statements can't be grouped. The config params are already reused.

**Comment by aseemavi** [comment]
based on above comment, do we want to close this issue?

**Comment by mjethanandani** [comment]
The issue (duplicated here) is:

Is it possible to reduce the duplication of the filter cases for
named classifiers and inline classifiers? The constraints on both
also seem to differ.

One suggestion was to use a grouping, but that does not address the underlying issue. Is there a way to reduce the actual duplications between the named and inline filter classes?

**Comment by aseemavi** [comment]
We augment one to classifier template and one to inline policy (i.e. policy directly). This is to support both flavor of the model. I don't see if anything else can be done here.
