### ISSUE TITLE
Groupings are used once

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/qos-yang#83]
Groupings such as conform-2color-meter-action-params are used only once. They should be removed and made inline with its corresponding uses statement.

Same for exceed-2color-meter-action-params, one-rate-two-color-meter, one-rate-tri-color-meter, two-rate-tri-color-meter,

**Comment by aseemavi** [comment]
in the new proposal, converted these to single name "meter-action-params". Now, it is being reused.
